### PR TITLE
Append to body instead of image parent

### PR DESCRIPTION
**Pull request by spinningarrow**
Should fix https://github.com/fat/zoom.js/issues/77

### CODE REVIEW

**Comment by spinningarrow** [comment]
Original CodePen by @ElegantSudo: http://codepen.io/yipyop/pen/RRpOKQ
CodePen with this fix: http://codepen.io/spinningarrow/pen/NAjyrN

Notes:
- Tested on desktop Chrome (latest) and iOS Safari
- Haven't tested the performance but seems to be working fine
- There's an unrelated issue where `dispose` is called multiple times - looks like the old refs aren't being cleaned up

**Comment by heavybeard** [comment]
It seems a really good fix.
For merging it requires more test, right?

**Comment by spinningarrow** [comment]
Yup, more testing would be good! @ElegantSudo was talking about doing this in a performant way so I'd like to hear their views.

**Comment by ElegantSudo** [comment]
This is an awesome PR! I'm going to take a close look at the code this weekend and see if I can fix a few things. As far as I can tell, it's performant.

Solved Issues:
- [ ] Depending on viewport dimensions, the image will scale past the viewport.
- [ ] Appending the image to the document body means nested CSS code won't work with the image's style. This means that if the original image doesn't have its defined height on the DOM node, the appended image (`.zoom-img`).

    - If we don't fix this, we should make this clear in the readme.
    - To fix this, we can take all of the necessary styles of the original image element and apply them to the appended image element.

**Comment by spinningarrow** [comment]
@ElegantSudo 

> Depending on viewport dimensions, the image will scale past the viewport.
Small viewport = works fine.
Large viewport = problem. 

Could this be a CodePen issue? I see it on CodePen, but not if I wrap one of the images on the demo page in a `<div style="overflow: hidden">` and view it normally in my browser. The max viewport I tested with is approximately 1920x1200.

> Appending the image to the document body means nested CSS code applied to the original image […]

Personally I'm fine with this – imho this is supposed to be a minimalist effect for simple websites. We could mention it somewhere in the readme.

> Because the offset (top, left) are calculated relative to the parent element and not the viewport, sometimes the image won't zoom from the correct place on the user's screen if there's nested elements and scroll involved.

I need to test this myself; I admit I've only tried on simple layouts so far. Is this a bug introduced by this change or is it a general problem from before?

**Comment by spinningarrow** [comment]
@ElegantSudo @heavybeard Just realised the issue with the height is because the aspect ratio of the image has not been maintained in the thumbnail. I'm willing to let this go as a 'known issue'.

**Comment by ElegantSudo** [comment]
> @ElegantSudo @heavybeard Just realised the issue with the height is because the aspect ratio of the image has not been maintained in the thumbnail. I'm willing to let this go as a 'known issue'.

@spinningarrow valid point! AFAIK the fix to the offset should be easy. I'll check it out.

**Comment by spinningarrow** [comment]
@ElegantSudo Sounds good! In that case, I'm going to merge this in now. The offset issue can be fixed separately since this one was about appending the zoomed image to the body, and it looks like the offset issue exists irrespective of that.

**Comment by ElegantSudo** [comment]
I've fixed the issue, but I'm a little new to contributing to Github. How can I make a pull request for just your fork, and not the main one?

**Comment by spinningarrow** [comment]
Did you fork the original repo or this one? If it was this one, it should be selected by default when you try to create a pull request.

Either way, you can paste the link to the commit on github and I can take a look.

**Comment by heavybeard** [comment]
Hi @ElegantSudo , hi @spinningarrow,
I open an issue on my fork (that have some many feature). I want to add your "append-to-body" code.
If you want to try it, this is the fork https://github.com/heavybeard/zoom-vanilla.js/ and this is the issue https://github.com/heavybeard/zoom-vanilla.js/issues/4

Thanks

**Pull request merged**
