### PR TITLE
fix viewport offset

### PR DESCRIPTION
**Pull request by ElegantSudo**
Fixed the viewport offset issue.

### CODE REVIEW

**Comment by ElegantSudo** [comment]
@spinningarrow how does this look?

**Comment by spinningarrow** [comment]
Looks good to me!

Do you have an example CodePen where this works but the original doesn't?

**Comment by ElegantSudo** [comment]
@spinningarrow 

Broken: http://codepen.io/yipyop/pen/vKkEbR
Fixed: http://codepen.io/yipyop/pen/ZOyYkQ

**Comment by heavybeard** [comment]
Maybe I have the same issue here http://heavybeard.github.io/zoom-vanilla.js/dist/
On the bottom I have added the zoom on video and it isnt fixed on viewport

ps: when all issues opened in last weeks are closed, I'll try to added on my fork

**Comment by spinningarrow** [comment]
@ElegantSudo That looks fantastic. Merging it in. Thanks a lot!

**Comment by spinningarrow** [comment]
@heavybeard Yes, it's possible. I've merged this in now!

**Pull request merged**
