### PR TITLE
Feature/video

### PR DESCRIPTION
**Pull request by heavybeard**
Add new feature: zoom on video too

### CODE REVIEW

**Comment by spinningarrow** [comment]
Thanks for being so active on this project!
Just wondering - is this something that came from upstream (`fat/zoom.js`) or our own thing?

**Comment by spinningarrow** [comment]
Btw, the video files have made this repository super heavy. What do you say to using some already-hosted video files instead?

**Comment by heavybeard** [comment]
this is a new feature developed by me with a pull request here https://github.com/fat/zoom.js/pull/66

I tested it on multiple browsers and mobile too and it works well, so I decide to merge on master project.

I can upload tomorrow other videos (<5mb) or I can try to link to an extarnal resource

**Comment by spinningarrow** [comment]
I've uploaded smaller videos now as a part of #12.

**Comment by heavybeard** [comment]
Many thanks

**Comment by ElegantSudo** [comment]
@spinningarrow could you take a look at this? I've been trying to create a solution, but it's been a pretty hard challenge to solve. https://github.com/fat/zoom.js/issues/77

**Comment by spinningarrow** [comment]
@ElegantSudo could you give me a codepen or something that demonstrates the problem? I mostly need it for testing.

**Comment by ElegantSudo** [comment]
@spinningarrow of course! http://codepen.io/yipyop/pen/RRpOKQ

**Comment by spinningarrow** [comment]
Looks good! Thanks a lot; I'll take a crack at it.

**Comment by spinningarrow** [comment]
@ElegantSudo take a look at #18 when you can!

**Pull request merged**
