### PR TITLE
Merge from master

### PR DESCRIPTION
**Pull request by heavybeard**

### CODE REVIEW

**Comment by spinningarrow** [comment]
Thanks once again for this! I'm thinking that having two branches exactly the same makes no sense; there is always a chance that something committed to `master` will be forgotten to be merged to `gh-pages`. So I'm thinking of having only one branch called `gh-pages` (unfortunately it has to be called that so that the demo on GitHub Pages works properly). What do you say?

**Comment by heavybeard** [comment]
I think is better divide the two branches (like now) and merge `master` on `gh-pages` for following the "GitHub rules"

**Comment by spinningarrow** [comment]
But doesn't it make the maintenance more arduous? Even right now the two
branches are not in sync.

**Comment by heavybeard** [comment]
Someone use gh-pages for documentation or we can try to use the git-flow tech for managing the branches. Try to google it, now I'm on mobile, sorry

**Comment by spinningarrow** [comment]
@heavybeard Of course, I know about Git Flow however it's way to much overhead for this kind of a project.

Where I'm coming from is that for _this_ particular project, the two branches will always be the same (because that makes sense). So we might as well have only one branch to keep things simple.

**Comment by heavybeard** [comment]
You're right! Less is more, so I approve it. Try and let me know.
When you have done, I'll optimize the code (because now is very ugly) and write an helpful documentation in a new branch `documentation`

**Comment by spinningarrow** [comment]
All right, I'm done. `gh-pages` is the default branch now. Please refer to #12 for a description of the changes, and do let me know there if everything is okay. Thanks!

**Pull request merged**
